### ISSUE TITLE
Evolution object with multiple numeric arguments leaks internal symbols

### ISSUE THREAD

**Issue by maxitg** [maxitg/SetReplace#160]
The following
```wl
In[] := WolframModel[{{1, 2}} -> {{1, 3}, {1, 3}, {3, 2}}, {{1, 1}}][1, 2]
```
![image](https://user-images.githubusercontent.com/1479325/71302999-8f964f00-2380-11ea-97d4-65e57ffa8d14.png)
leaks internal symbols.

**Expected behavior**
A message should be produced, and the result should remain unevaluated.

**Version**
 - OS: macOS 10.15.2 (19C57)
 - Wolfram Language Version: "12.1.0 for Mac OS X x86 (64-bit) (December 16, 2019)"
 - SetReplace git sha: 6c825ffae94ac256666e777bb5671a108c2d539b

**Comment by daneelsan** [comment]
So if I pass an integer to a `WolframModelEvolutionObject`, no more arguments should be allowed, right?
What would a sensible error message be? Perhaps something like `Pargx` `"Property 1 requested with 2 arguments; 0 arguments are expected"`

![image](https://user-images.githubusercontent.com/40190339/95951392-f4adac00-0dbb-11eb-94bd-62aff9188f4a.png)

**Comment by maxitg** [comment]
@daneelsan, I think this message is confusing. It would be better to say something like ``"WolframModelEvolutionObject[...] is called with `n` arguments. Either 1 argument is expected for implicit "Generation", or a property name is expected as the first argument."``.
