### ISSUE TITLE
NodeNamingFunction renames atoms instead of vertices

### ISSUE THREAD

**Issue by maxitg** [maxitg/SetReplace#174]
**Describe the bug**
`"NodeNamingFunction"` should rename vertices instead of atoms. I.e., the following
```
In[] := WolframModel[<|
  "PatternRules" -> {{a_}, {b_}} :> {{f[
       x]}}|>, {{10}, {11}}, "FinalState", 
 "NodeNamingFunction" -> All]
```
```
Out[] = {{f[3]}}
```
should instead produce `{{3}}`.

**Version (please complete the following information):**
 - OS: 10.15.2 (19C57)
 - Wolfram Language Version: "12.1.0 for Mac OS X x86 (64-bit) (December 21, 2019)"
 - SetReplace git sha: ba9234cd62794ef55cd9473320ec7eeb9473e21e

**Comment by daneelsan** [comment]
Is this outdated? I don't see `"NodeNamingFunction"` anywhere in the code.
