### ISSUE TITLE
Incorrect list nesting in WL WolframModel

### ISSUE THREAD

**Issue by maxitg** [maxitg/SetReplace#259]
The following ignores the nesting of the input:
```wl
In[] := WolframModel[{1 -> {{2}}, {{1}} -> 2}, {{{{{1}}}}}, 3, "StatesList"]
Out[] = {{{{{{1}}}}}, {{1}}, {{2}}, {{3}}}
```

It should instead return the following because the nesting of the input should not be matched by any of the rules.
```wl
Out[] = {{{{{{1}}}}}}
```

**Version:**
 - OS: macOS 10.15.3 (19D76)
 - Wolfram Language Version: "12.1.0 for Mac OS X x86 (64-bit) (March 5, 2020)"
 - SetReplace git sha: 8e6f38606af1ee2bd07b192d086a5b43974e6375

**Comment by daneelsan** [comment]
It seems to me that the issue is in `toPatternRules`, where:
```
vertexPatterns = Pattern[#, Blank[]] & /@ newVertexNames;
```
should be:
```
vertexPatterns = Pattern[#, Except[Blank[List]]] & /@ newVertexNames;
```

with that change, these work as intended:
```
In[]:= WolframModel[{1 -> {{2}}, {{1}} -> 2}, {{1}}, 3]["StatesList"]

Out[]= {{{1}}, {2}, {{3}}, {4}}

In[]:= WolframModel[{1 -> {{2}}, {{1}} -> 2}, {{{1}}}, 3]["StatesList"]

Out[]= {{{{1}}}}

In[]:= WolframModel[{1 -> {{2}}, {{1}} -> 2}, {{{{1}}}}, 3]["StatesList"]

Out[]= {{{{{1}}}}}

In[]:= WolframModel[{1 -> {{2}}, {{1}} -> 2}, {{{{{1}}}}}, 3]["StatesList"]

Out[]= {{{{{{1}}}}}}
```

Having said that... `ToPatternRules` loses its "charm" (those ugly `Except`):
```
In[28]:= ToPatternRules[{{1, 2, 3}, {2, 4, 5}} -> {{5, 6, 1}, {6, 4, 
    2}, {4, 5, 3}}]

Out[28]= {{v1 : Except[_List], v2 : Except[_List], 
   v3 : Except[_List]}, {v2 : Except[_List], v4 : Except[_List], 
   v5 : Except[_List]}} :> 
 Module[{v6}, {{v5, v6, v1}, {v6, v4, v2}, {v4, v5, v3}}]
```

**Comment by maxitg** [comment]
Now that I look at it, I'm not sure why did I think it was a weed. The first rule here just matches `{{{{1}}}}` as a single expression, and then creates `{1}`, where `1` is the new vertex name (which it is allowed to do because it's different from the vertex name in the input `{{{1}}}`).

So, it looks to me this works as intended and I'm going to close it if there are no objections. Sorry!
