### ISSUE TITLE
Support older versions like 11.3

### ISSUE THREAD

**Issue by freemin7** [maxitg/SetReplace#305]
### The problem
It is frustrating that i can't run the notebooks of the Wolfram Physics Project on version 11.3

### Possible solution
Back port support for this functionality to 11.3

### Alternative solutions
- Give out the upgrade to 12.0 for free. (unlikely).
- Put the relevant features into a kernel that could be called from 11.3 and other older versions.
- Provide information how WolframEngine might be used to work on Wolfram Physics Project and execute their notebooks

### Additional context
Wolfram Physics Project seems to be a vanity project of Mr. Wolfram. If he wants to help with people researching this having the tools more accessible would be necessary.

**Comment by freemin7** [comment]
I found out you could access 12.0 functionality via Wolfram Engine just as the Readme suggested.
It is also possible to use Wolfram Engine that as a Jupyter kernel.
This use seems sanctioned by Wolfram as the plugin is provided by them.
This requires agreeing to additional license conditions, i think the condition "Conduct personal projects at home, at school, at work" applies to me." applies to what i want to do.

This however locks oneself outside the cdf world.

**Comment by maxitg** [comment]
I'm happy that works for you. Some functions here (like `RulePlot[WolframModel[...]]`) require 12.1, but Wolfram Engine 12.1 is coming soon (hopefully next week).

And yes, contributing to the Physics Project is absolutely an allowed use case for Wolfram Engine. You can also try using [Wolfram Cloud](https://www.wolframcloud.com) if you want to see notebooks. It's running 12.1 and already has SetReplace installed (evaluate ``<< SetReplace` `` to get started).

**Comment by freemin7** [comment]
If i am not mistaken the compute time per cell in the cloud is limited to a minute?
Or something like that. I find that my usual calculations so far are like 15 min+. Do you know more about the free compute limits of Wolfram Cloud?

**Comment by maxitg** [comment]
Yes, it is limited to 1 minute on a free plan. You can see the limits if you open Plan Details [here](https://account.wolfram.com/products/wolfram-cloud).

**Comment by freemin7** [comment]
Thanks for addressing this issue so clearly and competently. 
I see myself as an early adopter who can tell you what someone to the problems might one bump into. I am not trying to make your life hell ;-)
