### ISSUE TITLE
C++ Style Checking in CI

### ISSUE THREAD

**Issue by aokellermann** [maxitg/SetReplace#316]
### The problem
It would be best if we could automate the checking of C++ code style in CI. This would allow PR reviewers to spend less time manually linting. 

### Possible solution
Add a cpplint step to automated CI test. Linter script must be installed on CI Docker image as well.

**Comment by phcerdan** [comment]
Have a look as well to github actions and clang-format: https://github.com/marketplace/actions/clang-format-lint
