### ISSUE TITLE
Refactor C++ Formatting

### ISSUE THREAD

**Issue by aokellermann** [maxitg/SetReplace#319]
### The problem
The repository's code does not conform to Google's [formatting style](https://google.github.io/styleguide/cppguide.html#Formatting).

### Possible solution
Refactor all C++ formatting to adhere to the proper formatting style.

This issue is a subset of #317.

**Comment by phcerdan** [comment]
This is great, I would recommend to add a `.clang-format` file to the top level with the chosen style (Google). It integrates very well with IDE's and editors.
We can also use any already developed github action to enforce it in the CI.
