### ISSUE TITLE
Causal invariance

### ISSUE THREAD

**Issue by freemin7** [maxitg/SetReplace#321]
### The problem
For WFPP (Wolfram Fundamental Physic Project) you often want to work on causal invariant rules. There should be a way to check whether a rule satisfies the constraints necessary for WFPP (which you know better than i do)

### Possible solution
Add function which statically check a rule whether they violate some constraints on the rules.

### Alternative solutions
Provide a function which checks whether a rule a casually invariant for a certain seed by expanding it in different ways and check whether they turn out the same over fixed number of generations

### Additional context
https://mathworld.wolfram.com/CausalInvariance.html Although it is quiet sparse.

**Comment by GetJonWithIt** [comment]
https://resources.wolframcloud.com/FunctionRepository/resources/CausalInvariantQ/
https://resources.wolframcloud.com/FunctionRepository/resources/TotalCausalInvariantQ/

**Comment by GetJonWithIt** [comment]
Does this feature propose any additional functionality beyond the existing CausalInvariantQ and TotalCausalInvariantQ functions? If so, please specify.

**Comment by freemin7** [comment]
In so far as `TotalCausalInvariantQ` can not be computed in a symbolic manner indepent of the numbers of generations. The existing functionality, i was not aware of, is identical to what i proposed.

Are you aware of index of all WolframLanguage functionality central to Wolfram's project?

**Comment by GetJonWithIt** [comment]
Determining causal invariance is an undecidable problem in general, so it is not possible to have a deterministic function without an explicit step count that is guaranteed to terminate in finite time.

All of the functionality that we have developed as part of the physics project, as well as some related system symbols, are indexed here (as I mentioned in your previous issue regarding hypergraph dimensionality): https://www.wolframcloud.com/obj/wolframphysics/Tools/guide-page

-Jonathan

**Comment by freemin7** [comment]
I will read the guide-page more properly this time.
How can i find what Package Spec i need to install to make a ResourceFunction["Bla"] available on my machine?

**Comment by GetJonWithIt** [comment]
All of our function repository entries should be completely standalone (or, at least, all of the ones with my name on them certainly are), so no external packages should be necessary. -J
