### ISSUE TITLE
rule vs rules

### ISSUE THREAD

**Issue by freemin7** [maxitg/SetReplace#322]
### The problem
The documentation on this repo defines the calling convention as:
`WolframModel[rule, initial set, step count]`
However https://resources.wolframcloud.com/FunctionRepository/resources/WolframModel defines it as:
`WolframModel[rules, initial set, step count]`

The syntax of rules is not defined, however it is a list of rules. That fact is not documented in an example. Furthermore the order of application of the rules is not documented.

### Possible solution

- Link to WolframModel documentation in the ReadMe.
- Give example of multiple rules in the WolframModel documentation on the Function Repository.
- Clarify order of application of multiple rules and when the order does not matter (is that equivalent to Causal Invariance?) Are there performance considerations decomposing a rule into multiple rules?

**Comment by justinjdickow** [comment]
This documentation is here FYI https://github.com/maxitg/SetReplace#multiple-rules

**Comment by freemin7** [comment]
Ok since i found the confusion unapproachable. I would suggest splitting the readme into different documentation md files. As it seems easy to overlook stuff.
