### ISSUE TITLE
Delete a node as a rule?

### ISSUE THREAD

**Issue by justinjdickow** [maxitg/SetReplace#329]
The thing I'm struggling to figure out is how to delete a node as a simple rule? For example, if I want to remove every self referential node {1, 1}, what is the rule?

I've tried `{{1, 1}->{}}` but received an error. I feel as though if I can figure this out combined with the multi rule functionality that I can greatly simplify my output plots

**Comment by aokellermann** [comment]
The rule
```wl
{a_, a_} :> {}
```
deletes two equal nodes. Is this the behavior you would like?

**Comment by aokellermann** [comment]
The rule
```wl
{{1,1}} -> {}
```
deletes self referential vertices.

**Comment by justinjdickow** [comment]
Thanks!
