### ISSUE TITLE
Short vertex indices in "ExpressionsEventsGraph"

### ISSUE THREAD

**Issue by maxitg** [maxitg/SetReplace#406]
### The problem
If one wants to see the indices of expressions and events in `"ExpressionsEventsGraph"`, one has to use `VertexLabels -> "Name"` option. However, that produces unnecessarily long labels, as the color of the vertex already tells one if it's an expression or an event:

```wl
In[] := WolframModel[{{{x, y}, {x, z}} -> {{x, z}, {x, w}, {y, w}, {z, 
      w}}}, {{0, 0}, {0, 0}}, 2]["ExpressionsEventsGraph", 
 VertexLabels -> "Name", ImageSize -> 600]
```
<img width="639" alt="image" src="https://user-images.githubusercontent.com/1479325/93524033-e9bd4400-f901-11ea-8994-bad9df242551.png">

It is in fact sufficient to only show the index. So, we should add an `"Index"` value which would do that.

### Possible solution
```wl
In[] := With[{graph = 
   WolframModel[{{{x, y}, {x, z}} -> {{x, z}, {x, w}, {y, w}, {z, 
         w}}}, {{0, 0}, {0, 0}}, 2]["ExpressionsEventsGraph", 
    VertexLabels -> "Name", ImageSize -> 600]}, 
 Graph[graph, VertexLabels -> (# -> Last[#] & /@ VertexList[graph])]]
```
<img width="399" alt="image" src="https://user-images.githubusercontent.com/1479325/93524169-183b1f00-f902-11ea-9b7d-1c1839b09a20.png">

**Comment by daneelsan** [comment]
Alternative:

```
WolframModel[{{{x, y}, {x, z}} -> {{x, z}, {x, w}, {y, w}, {z, 
      w}}}, {{0, 0}, {0, 0}}, 2]["ExpressionsEventsGraph", 
 VertexLabels -> Placed["Name", Automatic, Last], ImageSize -> 600]
```
![image](https://user-images.githubusercontent.com/40190339/95043375-3181f080-06a2-11eb-8ae4-44026f4606ad.png)
