### ISSUE TITLE
Subhypergraph

### ISSUE THREAD

**Issue by maxitg** [maxitg/SetReplace#412]
### The problem
`Subhypergraph` is a small utility function that selects hyperedges that only contain vertices from the requested list.

### Possible solution
```wl
Subhypergraph[h_, vertices_] := 
 Select[h, AllTrue[#, MemberQ[vertices, #] &] &]
```

```wl
In[] := Subhypergraph[{{1, 2, 3}, {2, 3, 4}, {3, 4, 5}}, {1, 2, 3, 4}]
Out[] = {{1, 2, 3}, {2, 3, 4}}
```

**Comment by taliesinb** [comment]
I suggest also `WeakSubhypergraph` that uses `AnyTrue` instead of `AllTrue`.
