### ISSUE TITLE
Build script fails from locations under symbolic links on Linux

### ISSUE THREAD

**Issue by maxitg** [maxitg/SetReplace#434]
### The problem
There are reports that the C++ compilation in `./build.wls` fails if the repository is located under a symbolic link. Specifically, because `FileNames` might be failing to find `*.cpp` files. We need to investigate further.
```sh
./build.wls
```
![](https://media.discordapp.net/attachments/762324239860367401/763153062960300032/unknown.png)

### Expected behavior
The build script should work with symbolic links. We might need a workaround for `FileNames`.

### Version
```wl
In[] := $OperatingSystem
Out[] = "Unix"
```

```wl
In[] := $SetReplaceGitSHA
```
d2aa6454e046af07179e2c767fab5569f2c1f5e6

**Comment by aokellermann** [comment]
I'm not able to reproduce this behavior.

[`AbsoluteFileName`](https://reference.wolfram.com/language/ref/AbsoluteFileName.html) resolves symbolic links.
