### ISSUE TITLE
IsomorphicHypergraphQ

### ISSUE THREAD

**Issue by daneelsan** [maxitg/SetReplace#480]
### The problem
Implement the `IsomorphicHypergraphQ` function, which tests isomorphism between two hypergraphs.
See:
   - https://resources.wolframcloud.com/FunctionRepository/resources/IsomorphicHypergraphQ
   - [Uniqueness Trees: A Possible Polynomial Approach to the Graph Isomorphism Problem](https://arxiv.org/pdf/1606.06399.pdf)

### Comment
The resource function works for _undirected_ hypergraphs.

### Possible Solution
```wl
In[]:= IsomorphicHypergraphQ[{{a, e, d}, {d, c}, {c, b}, {b, a}}, {{2, 4}, {4, 5, 1}, {1, 3}, {3, 2}}]
Out[]= True
```

```wl
In[]:= IsomorphicHypergraphQ[{{a, e, d}, {d, c}, {c, b}, {b, a}}, {{2, 4}, {4, 3, 1}, {1, 3}, {5, 2}}]
Out[]= False
```

**Comment by maxitg** [comment]
There is also [`IsomorphicOrderedHypergraphQ`](https://resources.wolframcloud.com/FunctionRepository/resources/IsomorphicOrderedHypergraphQ), but I don't know if it works.
