### ISSUE TITLE
RandomHypergraph

### ISSUE THREAD

**Issue by daneelsan** [maxitg/SetReplace#510]
### The problem
Implement the `RandomHypergraph` function.

### Possible solution
A possible implementation and API is found in the [WFR](https://resources.wolframcloud.com/FunctionRepository/resources/RandomHypergraph):

```wl
RandomHypergraph[{n_Integer, {e_Integer, a_Integer}}] := 
 RandomInteger[{1, n}, {e, a}]

RandomHypergraph[{n_Integer, sig : {{_Integer, _Integer} ..}}] := 
 Catenate[RandomInteger[{1, n}, #] & /@ sig]
```

![image](https://user-images.githubusercontent.com/40190339/97930946-93ce1f80-1d3a-11eb-81fb-d4a417cb6739.png)

```wl
In[]:= RandomHypergraph[{10, {5, 2}}]
Out[]= {{5, 4}, {7, 8}, {7, 6}, {7, 1}, {4, 9}}
```

```wl
In[]:= RandomHypergraph[{10, {{5, 2}, {4, 3}}}]
Out[]= {{1, 2}, {2, 9}, {6, 1}, {3, 3}, {10, 10}, {1, 8, 8}, {5, 7, 9}, {5, 
  7, 6}, {5, 3, 3}}
```

**Comment by maxitg** [comment]
I think another useful API would be just specifying the total number of hyperedge parts (essentially, the "complexity").

E.g., for `{{1, 2, 3}, {3, 4}, {4, 5, 6}}`, this number will be 8.

This way, one can generate any possible hypergraph by varying just one parameter. This will be even more useful for enumeration.

**Comment by maxitg** [comment]
It might also be useful to generate connected hypergraphs (maybe with an option).
