### ISSUE TITLE
Dynamic check for no branching

### ISSUE THREAD

**Issue by maxitg** [maxitg/SetReplace#54]
Implement checking that no multiway branching occurs in a `WolframModel` evolution.

There are two non-trivial checks that will need to be implemented: one for necessary and one for sufficient conditions.

## Necessary condition

For the necessary condition, we need to make sure there is at most one match for every vertex. However, it is possible that the matches that appear different are actually the same, for instance, `{{0, 0}, {0, 0}, {0, 0}}` can match in multiple ways to `{{a_, b_}, {c_, d_}, {e_, f_}}`, however, all these matches would produce the same result if evaluated.

Further, it is possible that the rule would preserve symmetry, so, for instance, `{{a_, b_}, {a_, c_}, {a_, d_}} -> {}` would be confluent if matching degree-3 vertices, even though it can be matched multiple ways.

This must be fast enough to be always on during evaluation.

*This (though no fast) was implemented during WSS19.*

## Sufficient condition

Sufficient condition is more tricky. It has to do with space-like pairs of events that do not simultaneously exist in a current evolution state of the system. For instance, consider the following toy example:
```wl
In[] := SetReplace[{1, 2}, {{1, 10} :> {X}, {x_} :> {x + 2}}, 40]
```
This system does branch, as it is possible to either evolve both numbers simultaneously and get
```wl
Out[] = {41, 42}
```
or it is also possible to evolve `2` 4 times, and then use the first rule to get
```wl
Out[] = {X}
```

Hence, it is not sufficient to check duplicate matches between existing subsets of expressions, we need to consider past ones as well. Specifically, we need a fast way to identify if a pair of events is spacelike or timelike (i.e., if a pair of events is causally related).

This probably cannot be always fast, so they could be an option to turn this on and off.

*This was **not** implemented during WSS19.*

**Comment by maxitg** [comment]
Duplicate of #59.

**Comment by maxitg** [comment]
Both of these can now be done using `"EventSelectionFunction" -> "MultiwaySpacelike"` and `"EventDeduplication" -> "SameInputSetIsomorphicOutputs"`.

It would be useful, however, to have a property that would check for multiway branching, i.e.,

```wl
In[] := evolution["MultiwayQ"]
Out[] = False
```

would mean both of the checks above are satisfied (of course, depending on the event ordering function and the number of generations, there could be possible matches in the future which would change the answer, but that's expected for this issue).

**Comment by daneelsan** [comment]
Should this be closed now that https://github.com/maxitg/SetReplace/pull/503 is merged?

**Comment by maxitg** [comment]
Yes, good catch!
