### ISSUE TITLE
Random performanceTest.wls failure "git tree must be clean"

### ISSUE THREAD

**Issue by maxitg** [maxitg/SetReplace#573]
### The problem
Performance Test step sometimes fails on CI with "Current git tree must be clean.": [example](https://app.circleci.com/pipelines/github/maxitg/SetReplace/1475/workflows/96174e1e-53df-4ece-95fc-15baa2983588/jobs/2242)

```
#!/bin/bash -eo pipefail
./performanceTest.wls master @HEAD 2
Current git tree must be clean.
The product exited because an error occurred. For a product older than 12.1, this can mean that the product is unregistered.

Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by aokellermann** [comment]
@maxitg what does `@HEAD` mean? `@` is a synonym for `HEAD` I believe, so this looks wrong to me.

**Comment by maxitg** [comment]
This issue has never happened since then, however, `./performanceTest.wls` is indeed broken in this case because it fails with `HEAD` and silently fails with `@HEAD` by running the tests on the same branch again (so the performance report is always at zero).
