### ISSUE TITLE
Using multiple rules ignores RandomSeeding in WolframModel

### ISSUE THREAD

**Issue by maxitg** [maxitg/SetReplace#642]
### The problem

`RandomSeeding` is ignored in some cases in `WolframModel`.

For example:

```wl
In[] := Counts @ Table[
  BlockRandom[
    WolframModel[<|"PatternRules" -> {{{1, 2}} -> {}, {{2, 3}} -> {}}|>,
                 {{1, 2}, {2, 3}},
                 <|"MaxEvents" -> 1|>,
                 "EventOrderingFunction" -> "Random"]["FinalState"],
    RandomSeeding -> 123],
  100]
Out[] = <|{{2, 3}} -> 95, {{1, 2}} -> 5|>
```

produces different results every time it's run. However, doing the same with a single rule (which is equivalent in this case), produces consistent results as expected:

```wl
In[] := Counts @ Table[
    BlockRandom[
      WolframModel[<|"PatternRules" -> {{{a_, b_}} :> {}}|>,
                   {{1, 2}, {2, 3}},
                   <|"MaxEvents" -> 1|>,
                   "EventOrderingFunction" -> "Random"]["FinalState"],
      RandomSeeding -> 123],
    100]
Out[] = <|{{1, 2}} -> 100|>
```

### Expected behavior

Since the seed is specified, the result should always be the same.

### Version

```wl
In[] := SystemInformation["Small"]
```

<img width="729" alt="image" src="https://user-images.githubusercontent.com/1479325/118568460-7d6b3c80-b73d-11eb-851b-c416d9816517.png">

```wl
In[] := $SetReplaceGitSHA
```

c07dba14af76d7be0c71c60d9c96c1a7f41cae58

**Comment by daneelsan** [comment]
Could you share what `hypergraphConsensusRule` looks like? 😛

**Comment by maxitg** [comment]
@daneelsan, oops, sorry, updated now to include the rule.

**Comment by maxitg** [comment]
It looks like this weed only appears if using multiple rules. I updated it with a minimal example.
